### ISSUE TITLE
Array functions don't support getters and setters

### ISSUE THREAD

**Issue by NeilFraser** [NeilFraser/JS-Interpreter#110]
a = [1, 2, 3, 4];
Object.defineProperty(a, 2, {get: function() {return 'hello';}});
alert(a.indexOf('hello'));

Expected result: 2
Actual result: -1

**Comment by mehulsatardekar** [comment]
Hi @NeilFraser i tried this on my machine your code actually working fine as expected. Don't know why you are getting result as -1. 
[
![node_test](https://user-images.githubusercontent.com/36101139/92416708-6ae73f00-f17c-11ea-99d6-9277b3d0c7ca.png)
](url)

**Comment by NeilFraser** [comment]
@mehulsatardekar Node is correct, it is giving the expected result of 2.  The JS-Interpreter however does not currently support getters and setters of arrays, so it returns -1.

I'm not too worried about this bug.  Code that uses getters and setters on arrays is -- dubious -- to say the least.  And fixing this in the Interpreter would mean a huge reduction in performance.

**Comment by NeilFraser** [comment]
Fixed.

**Comment by F1LT3R** [comment]
Did you take the hit on performance in fixing this issue? Or did it not make much difference?

**Comment by NeilFraser** [comment]
The plan was to leave this alone due to the cost-benefit ratio being not in our favour.  However, a different bug appeared which changed that ratio:

https://github.com/NeilFraser/JS-Interpreter/issues/207

Not allowing code that crashes the runtime is a hard requirement for JS-Interpreter.
