### ISSUE TITLE
Compiled-bundle version incompatible

### ISSUE THREAD

**Issue by uniibu** [NeilFraser/JS-Interpreter#113]
This code:
`  this.stateStack = [{
    node: this.ast,
    scope: this.global,
    thisExpression: this.global,
    done: false
  }];`  

is mangled by your minifier to:

`this.c=[{node:this.ca,scope:this.global,ua:this.global,done:!1}];`

So calling myInterpreter.stateStack.length will throw an error 
`Uncaught TypeError: Cannot read property 'length' of undefined`

I suggest to disable top-level name mangling on your minifier or use uglifyjs3 on its default options.

**Comment by NeilFraser** [comment]
The compressed version has been recompiled and this should be resolved.
