### ISSUE TITLE
Over 700 string array sort error

### ISSUE THREAD

**Issue by anhh** [NeilFraser/JS-Interpreter#118]
var a = ['a',.....]; // over 700 string item
a.sort();
// then "Maximum call stack size exceeded" error occurred

var a = ['a',...];
a.sort(function(a,b) {return a>b;})
// It is working.

**Comment by NeilFraser** [comment]
I've checked in an update that should resolve this, and speed up sort by roughly a factor of infinity.  Because it's a rather wide-ranging change to the way arrays function, I'll let this update bake for a week or so before recompiling the compressed version.
