### ISSUE TITLE
Adding associative arrays

### ISSUE THREAD

**Issue by cpetry** [NeilFraser/JS-Interpreter#121]
How would I add an enum defined like this to the interpreter:
`const Type = {
	NONE : 0,
	SOMETHING : 1,
};`

**Comment by cpcallen** [comment]
Do you mean in the code that you have the interpreter interpret?  If so, then just change `const` to `var` and it will work as expected.  (The interpreter only understand ES5.1; `const` is ES6.)

**Comment by cpetry** [comment]
Okay but how can I get access to it inside? It seems 'undefined'.
Do I have to create some inside object?

This is my initFunc when creating the interpreter:
`
var initFunc = function(interpreter, scope) {
interpreter.setProperty(scope, 'Type', Type);
};
`

**Comment by cpcallen** [comment]
>
> Okay but how can I get access to it inside? It seems 'undefined'.
> Do I have to create some inside object?
>
> This is my initFunc when creating the interpreter:
> var initFunc = function(interpreter, scope) {
> interpreter.setProperty(scope, 'Type', Type); };
>
Ahh, if you are trying to create such an object in an initFunc, you will
need to use interpreter.createObjectProto or interpreter.nativeToPseudo
(the latter is probably easier and more appropriate for your use-case).

But it would be much easier just to prepend the 'var Type = { .... }'
command to the input to the interpreter.
