### ISSUE TITLE
Thread demo broken with latest commit

### ISSUE THREAD

**Issue by jandrewb** [NeilFraser/JS-Interpreter#122]
The thread demo does not appear to work with the latest version of the project. Is there another way to do the same thing, or is that feature no longer available?

**Comment by NeilFraser** [comment]
Seems to work for me on the latest version.  What are the symptoms you see?

**Comment by jandrewb** [comment]
The code in my threads would not run. So I finally replaced acorn_interpreter.js with the acorn.js and interpreter.js from the live demo, and it started working.

**Comment by jandrewb** [comment]
So my original problem was that I used the compressed acorn_interpreter.js. Apparently the compression changed variable names used by the thread.html example, or something.

However, calling functions defined within the parsed code still seems to be broken in the thread.html example. It's a shame because this is such a cool feature. Any chance there is an easy fix?

**Comment by NeilFraser** [comment]
I've recompiled and pushed the latest version.  But I'm still not able to recreate this issue.  Can you give detailed reproduction instructions for this page:
https://neil.fraser.name/software/JS-Interpreter/demos/thread.html

Thanks.

**Comment by jandrewb** [comment]
Paste this code into #1 thread, hit parse, hit step several times. The alert does not show, but I get a Javascript error on the page saying the function "test" is not defined. The same code works on the normal demo. I am running on Safari.
 
function test(){ alert('worked!'); }
test();

**Comment by NeilFraser** [comment]
That explains why I couldn't recreate this error, I normally use the `var f = function() {...};` syntax (which works) rather than the `function f() {...}` (which does not work).

Thanks for clarifying.  Investigating...

**Comment by NeilFraser** [comment]
Should be resolved now.  Not a problem with the interpreter, the thread demo was broken.
