### ISSUE TITLE
Free space used by appended code after execution has finished

### ISSUE THREAD

**Issue by CesMak** [NeilFraser/JS-Interpreter#124]
Hey there,

I have a library containing many simple functions like e.g:

```JS
function size(a,b){
  return a+b;
}
// .... 
```

For testing this library  I have a html textarea where I simply want to write the funtions names like this:

```JS
size(3,2);
size(3,1);
```

It would be really nice, If I could just simple test my library like this:
```JS
var myInterpreter = new Interpreter("var result= 0;function size(a, b){return a+b;}");
myInterpreter.run('size(3,2); size(3,1)');
```

where the .run function gives me an array of the results for each input.

But what I currently have to do using this library is:

```JS
myInterpreter.appendCode('(size(3,4));');
myInterpreter.run();
console.log(myInterpreter.value);
```

So I actually want to have the results outside the sandbox. And using my method is not quite good I think because If I add more and more functions with .appendCode the program will get slower and slower....

That is why I want to ask in order to test a single function's result quite fast if there is a method to delete the .appended Code ? 

Thanks for your comments
Markus

**Comment by cpcallen** [comment]
If `myInterpreter.value` is a primitive it is directly usable outside the sandbox, like any other primitive JS value.  (If it is an object then unfortunately this is not directly possible, and nor is it possible to convert it to a native object with full generality, but in most cases it can be converted to a useful approximation using `pseudoToNative`.

It would be nice if the interpreter would automatically dispose of appended code once the code was no longer needed; I will leave this open as a feature request for that feature.

It's worth noting that dead code will not directly slow the interpreter down; it only wastes a (fairly small) amount of memory.

**Comment by NeilFraser** [comment]
Fixed.
