### ISSUE TITLE
Listing all declared variables

### ISSUE THREAD

**Issue by g-arais** [NeilFraser/JS-Interpreter#127]
How I get a list of all declared variables on a parsed javascript code?

**Comment by NeilFraser** [comment]
On the demo page:
  https://neil.fraser.name/software/JS-Interpreter/
press 'parse', open the console, and type:
  `myInterpreter.global.properties`
You will get a hashmap of all global variables and their values.  Most of this list are the built-in variables (like `Math` and `parseFloat`), but it also includes user variables (in this case `result` and `fibonacci`).
