### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by jackschaedler** [NeilFraser/JS-Interpreter#128]
No issue, just wanted to thank you for your hard work, and for making this code available for free use. I was able to use it to create https://jackschaedler.github.io/jazzari, which you might find amusing!

**Comment by NeilFraser** [comment]
Very cool, thanks for showing me.

A couple of suggestions:
There are a lot of missing semicolons in the example programs.
I think the play/stop icons should be white, not the colour of the currently selected instrument.  By matching the current colour it implies that only that instrument will be paused or played.

You might be interested in the music app that I'm making:
https://music-dot-blockly-games.appspot.com/music?lang=en
It also uses the JS-Interpreter.  Still a work in progress: help, visualization, internationalization, and level 10 all have known issues.

**Comment by jackschaedler** [comment]
Hi Neil,

Great suggestions, I'll think about making these changes soon!

This is really neat. Great work on the details like the note dropdown chooser that shows the staff. Wonderful!
