### ISSUE TITLE
External Higher Order Functions

### ISSUE THREAD

**Issue by FynnMazurkiewicz** [NeilFraser/JS-Interpreter#130]
Hey everyone! 😊 

I'm trying to use higher order functions.
I created a higher-order function outside of the interpreter and exposed it to the sandbox.
However, this fails because the higher order function receives the psuedoFunction and therefore can't call it (`TypeError: fn is not a function`).

A minimal test case:
```javascript 
var myCode = 'wrapper(function(){});';
var initFunc = function(interpreter, scope) {
    var wrapper = function(fn) {
        fn();
    };
    interpreter.setProperty(scope, 'wrapper',
        interpreter.createNativeFunction(wrapper));
};
var myInterpreter = new Interpreter(myCode, initFunc);
myInterpreter.run();
```
I couldn't find any examples or documentation on how to handle this.
Sandboxed higher order functions work fine, of course.

Not sure if this is intended behaviour, but I would be more than thankful for any leads.

**Comment by NeilFraser** [comment]
Yes, this is a limitation of the interpreter, it is *really* hard for external JavaScript to initiate a callback into the interpreter.  The solution is to move the higher order function into the interpreted code.

Check out [Array.prototype.map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map).  This higher order function takes a function as an argument.  To achieve this the map function is written as a polyfill.  See the examples from line [869](https://github.com/NeilFraser/JS-Interpreter/blob/master/interpreter.js#L869) to line [1046](https://github.com/NeilFraser/JS-Interpreter/blob/master/interpreter.js#L1046).  There are a few more examples if you search for "this.polyfills_.push".

Feel free to reopen if you need more help.
