### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by amilajack** [NeilFraser/JS-Interpreter#135]
What are your thoughts on publishing this package to npm?

**Comment by abyx** [comment]
Yes please, seems like a basic requirement nowadays.

**Comment by NeilFraser** [comment]
Looks like someone has already done it, albeit with their own fork:
https://www.npmjs.com/package/js-interpreter
Though why it's got a dependency on 'clone' is anyone's guess.

I have no problem with other people creating and maintaining packages of JS-Interpreter on npm, bower, volo, ringojs, component, or whatever is hot this month, however I'm not really interested in dealing with the churn.  Personally I think the idea of uncontrolled code injection into your application is crazy, but apparently I'm currently in the minority.
