### ISSUE TITLE
Function .prototype and .length properties should be non-enumerable

### ISSUE THREAD

**Issue by cpcallen** [NeilFraser/JS-Interpreter#138]
The expressions `Object.getOwnPropertyDescriptor(function () {}, 'length').enumerable` and `Object.getOwnPropertyDescriptor(function () {}, 'prototype').enumerable` should both return false, but instead return true.

**Comment by NeilFraser** [comment]
Fixed with 0c0d71f2181c3ee9dce2a9e84227e20f478489bd
