### ISSUE TITLE
What's the best way to use this in node?

### ISSUE THREAD

**Issue by mercmobily** [NeilFraser/JS-Interpreter#142]
I am writing a software that requires admin users to provide some logic via code. Eval is obviously not a possibility. Has this been used in node? The js-interpreter package on npm seems pretty old...
Thank you!

**Comment by NeilFraser** [comment]
I don't know a lot about node, but the following seems to work in node:

```
var acorn = require('./acorn_interpreter');
var myInterpreter = new acorn.Interpreter('6 * 7;');
myInterpreter.run();
myInterpreter.value;
```

**Comment by mercmobily** [comment]
I am lost... and sorry for the bother!
Which bits are yours, and which bits are Acorn's?
Or, who wrote acorn_interpreter? And why is it distributed minimised?
I am a bit lost as which bit is what... sorry for the bother again!

**Comment by NeilFraser** [comment]
Good point, node doesn't benefit from using the minimised version.  This is clearer:

```
var acorn = require('./acorn');
var JSInterpreter = require('./interpreter');
var myInterpreter = new JSInterpreter.Interpreter('6 * 7;');
myInterpreter.run();
myInterpreter.value;
```

**Comment by cpcallen** [comment]
To expand slightly on Neil's comment: [Acorn](https://github.com/acornjs/acorn) is a JS parser written by (Marijn Haverbeke)[https://marijnhaverbeke.nl/]; JS-Interpreter was written by @NeilFraser and uses Acorn for parsing.  `acorn_interpreter.js` is just the result of applying (closure-compiler)[https://developers.google.com/closure/compiler/] to the two.
