### ISSUE TITLE
Failure to wrap a value

### ISSUE THREAD

**Issue by jaunt** [NeilFraser/JS-Interpreter#148]
Hello, thanks for your time.  I'm probably misunderstanding things, but I can't understand why this isn't working.  Would greatly appreciate some direction:

```
function initializeInterpreter(interpreter, scope) {
        function myWrapper(a, b, c) {
          return a + b + c
        }
        interpreter.setProperty(
          scope,
          "testAdd",
          interpreter.createNativeFunction(myWrapper)
        )
}
var myCode = "testAdd(1,2,3)"
var myInterpreter = new Interpreter(myCode, initializeInterpreter)
myInterpreter.run()
alert(myInterpreter.value)
```

The above works and alerts "6", but if I try to assign testAdd to a variable in myCode, it says "Failure to wrap a value".

```    
function initializeInterpreter(interpreter, scope) {
        function myWrapper(a, b, c) {
          return a + b + c
        }
        interpreter.setProperty(
          scope,
          "testAdd",
          interpreter.createNativeFunction(myWrapper)
        )
}
var myCode = "var x=testAdd(1,2,3)"
var myInterpreter = new Interpreter(myCode, initializeInterpreter)
myInterpreter.run()
alert(myInterpreter.value)
```

Thoughts?

Thanks!

**Comment by jaunt** [comment]
Looks like if I pass false to the second argument of createNativeFunction, it works.  I didn't see any of the demos doing that so I'm a little confused.

**Comment by jaunt** [comment]
Ok, progress.  I found this in an obscure gist I stumbled on.  Is it documented and I just missed it?

return interpreter.createPrimitive(a + b + c);

**Comment by NeilFraser** [comment]
Oh, that's helpful.  The fact that createPrimitive does something indicates that you have an extremely old (more than one year) copy of the interpreter.  Looking at [the source code](https://github.com/NeilFraser/JS-Interpreter/blob/master/interpreter.js#L3593):

```
// Obsolete.  Do not use.
Interpreter.prototype['createPrimitive'] = function(x) {return x;};
```

**Comment by jaunt** [comment]
Thanks!  Sorry about that! 

I actually started wondering that myself, as I've been using the available npm package.  

So now I'm embarking on how to add this to my vue-js webpack project -- which I'm no expert at doing.  I'm currently pulling my hair out.

**Comment by NeilFraser** [comment]
That makes sense.  I've no idea who's behind the npm package, it's not ours.  That's kind of the problem with npm, it offers arbitrary code execution to anyone.
