### ISSUE TITLE
window.document.body.innerHTML

### ISSUE THREAD

**Issue by MarcWeber** [NeilFraser/JS-Interpreter#149]
https://neil.fraser.name/software/JS-Interpreter/demos/json.html
should have initGlobalScope set according to docs, but this simple snippet fails:
setOutput(window.document.body.innerHTML);

**Comment by NeilFraser** [comment]
Of course.  As it says in [the documentation](https://neil.fraser.name/software/JS-Interpreter/docs.html):

> None of the DOM APIs are exposed. That's kind of the point of a sandbox. If you need these, write your own interfaces.
