### ISSUE TITLE
Redo the same step

### ISSUE THREAD

**Issue by luismsaraiva** [NeilFraser/JS-Interpreter#150]
Hi,

I'm using the step function to run my code. I would like to know if it's possible to redo the same step x amounts of times?

Cheers

**Comment by NeilFraser** [comment]
Yes, this is possible, though it will significantly reduce execution speed.  Just before you perform every step, serialize the interpreter's state to JSON: https://neil.fraser.name/software/JS-Interpreter/demos/serialize.html
Then if you want to repeat a step, restore the state from your saved JSON, and execute step.

**Comment by luismsaraiva** [comment]
Thanks mate
