### ISSUE TITLE
serialize.js Throws Error When Used With acorn_interpreter.js

### ISSUE THREAD

**Issue by BeksOmega** [NeilFraser/JS-Interpreter#151]
### Problem Statement

Trying to serialize the Interpreter when using the minified acorn_interpreter file causes serialize.js to throw a cannot read property of undefined error.

### Steps to Reproduce

1. In [serialize.html](https://github.com/NeilFraser/JS-Interpreter/blob/208d182b3decdc2eae6b05ffbde20f9a926d7444/demos/serialize.html#L6) replace lines 6 & 7 
```
   <script src="../acorn.js"></script>
   <script src="../interpreter.js"></script>
```
with:
```
<script src="../acorn_interpreter.js"></script>
```
2. Follow the directions on the serialize.html page.

### Stack Trace

```
serialize.js:248 Uncaught TypeError: Cannot read property 'prototype' of undefined
    at serialize (serialize.js:248)
    at serializeButton (test.html:25)
    at HTMLButtonElement.onclick (test.html:116)
serialize @ serialize.js:248
serializeButton @ test.html:25
onclick @ test.html:116
```

### Aditional Information

Not sure if serialize.js is supported to the same level the interpreter is, or if it's more of a demo thing, but I figured I would send in an issue anyway. =)

**Comment by NeilFraser** [comment]
The serialization reaches deep into the interpreter; far beyond the public API.  As such, the compressed bundle is unintelligible to it.

Added documentation to call this out explicitly.  Thanks!
