### ISSUE TITLE
Import module in execution environment

### ISSUE THREAD

**Issue by grg121** [NeilFraser/JS-Interpreter#157]
Hello!

I would like to know if there is an easy way to import a js module (a file with variables & functions definitions) in order to be used by the interpreter.

I am using [filbert-js](https://github.com/differentmatt/filbert) to translate python code to javascript and I would like to execute these code in JS-Interpeter step-by-step. But Filbert generates js code such as:

```js
(function (__pythonRuntime) {
    {
        var __filbertRight0 = new __pythonRuntime
            .objects
            .tuple(1, 2, 3, 4);
        if (__filbertRight0 instanceof Array) {
            for (var __filbertIndex0 = 0; __filbertIndex0 < __filbertRight0.length; ++__filbertIndex0) {
                var i = __filbertRight0[__filbertIndex0];
                __pythonRuntime
                    .functions
                    .print('i: ', i);
            }
        } else {
            for (i in __filbertRight0) {
                __pythonRuntime
                    .functions
                    .print('i: ', i);
            }
        }
    }
})(filbert.pythonRuntime);
```

In order to correctly execute that code I would need the interpeter to load filbert module.

Can you help me with that?

Thank you so much

Best regards
Francisco N.

**Comment by cpcallen** [comment]
* Do whatever you need to do to read the contents of the filbert module into a string.
* Call `.appendCode(filbertModuleSourceCode)` to load it into the interpreter.
