### ISSUE TITLE
Binary expressions should evaluate the `valueOf()` of values, if present.

### ISSUE THREAD

**Issue by bioball** [NeilFraser/JS-Interpreter#166]
Take the following snippet:

```js
var obj1 = { valueOf: function () { return 5 } }
var obj2 = { valueOf: function () { return 3 } }
alert(obj1 - obj2);
```

I would expect this to alert `2`, but it alerts `NaN`.

This pattern is used for comparing `Date` objects, for example:

```js
var now = new Date('2019-05-07T16:45:17.000Z');
var then = new Date('2019-05-07T16:22:24.000Z');
var durationMs = now - then;
```

**Comment by NeilFraser** [comment]
Sadly, this is one of the limitations of a step-by-step interpreter.  There's no good way to call toString and valueOf functions implicitly.  This limitation is documented here:
https://neil.fraser.name/software/JS-Interpreter/docs.html

**Comment by bioball** [comment]
Hmm.. can this be done by pushing a CallExpression onto the stack? Similar to how getters and setters are used? Something like:

```js
if (leftValue === Object(value) && !state.doneValueOfLeft_) {
  state.doneValueOfLeft_  = true;
  const node = new this.nodeConstructor({ options: {} });
  node['type'] = 'CallExpression';
  const  state = Interpreter.State(node, scope);
  /** whatever else is needed to prepare the state */
  return state;
}
leftValue = state.value;
```

**Comment by cpcallen** [comment]
In principle yes—but consider that this would need to be done in every single place that the ES5.1 spec requires that either [ToPrimitive](https://www.ecma-international.org/ecma-262/5.1/index.html#sec-9.1) or [ToString](https://www.ecma-international.org/ecma-262/5.1/index.html#sec-9.8) specification methods be called—about 135 different places in all, including within builtin functions like `String()` (but also many others), which would have to be completely redesigned to be able to interact with the state stack.  It would be a *major* project.

**Comment by NeilFraser** [comment]
It's taken seven years, but this now works.
