### ISSUE TITLE
How to call class functions (React this.setState()) in the interpreter?

### ISSUE THREAD

**Issue by hsluoyz** [NeilFraser/JS-Interpreter#168]
I saw this example in: https://neil.fraser.name/software/JS-Interpreter/docs.html

But it's using a global function.

```js
    var myCode = 'alert(url);';
    var initFunc = function(interpreter, scope) {
      interpreter.setProperty(scope, 'url', String(location));

      var wrapper = function(text) {
        return alert(text);
      };
      interpreter.setProperty(scope, 'alert',
          interpreter.createNativeFunction(wrapper));
    };
    var myInterpreter = new Interpreter(myCode, initFunc);
```

How to call a class method? I hope we can support it officially.

As a workaround, I try to pass `this` pointer as a arg, but failed:

```js
function moveForward(ths) {
  let robot = ths.state.robot;
  if (robot.to === 0) {
    robot.y -= 1;
  ths.setState({
    robot: robot,
  });
}

class Example extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      classes: props,
      robot: {x: 2, y: 5, to: 1},
    };
  }

  runScript() {
    var initFunc = function(interpreter, scope) {
      interpreter.setProperty(scope, 'this', this);

      var wrapper = function(ths) {
        return moveForward(ths);
      };
      interpreter.setProperty(scope, 'move',
        interpreter.createNativeFunction(wrapper));
    };

    const myInterpreter = new Interpreter('move(this);', initFunc);
    myInterpreter.run();
    const output = myInterpreter.value;
    this.setState({
      output: output,
    });
  }
}

export default Example;

```

When `runScript()` is called, it returns error in browser:

```
TypeError: Cannot read property 'robot' of undefined

  25 | 
  26 | function moveForward(ths) {
> 27 |   let robot = ths.state.robot;
  28 |   if (robot.to === 0) {
  29 |     robot.y -= 1;
```

This is actually React code. But I think it has nothing to do with React. The general question is how to call class functions (which will modify class instance members) in the interpreter?

Can you help me?

**Comment by NeilFraser** [comment]
I've added a section to the docs on how to create API functions on an object:
https://github.com/NeilFraser/JS-Interpreter/commit/30c461d38c6d3111e7b9130cd5e80c04046cbe9c

Does this help?

**Comment by hsluoyz** [comment]
`createObjectProto` and `OBJECT_PROTO` is not defined.

**Comment by NeilFraser** [comment]
Good point.  That only works when using the uncompressed version.  I've updated the documentation with a more robust call:  https://github.com/NeilFraser/JS-Interpreter/commit/f72a7bdcc85487506423fc896b7be9972754fb3e
