### ISSUE TITLE
this.constructor() requires a proto

### ISSUE THREAD

**Issue by NAllred91** [NeilFraser/JS-Interpreter#175]
I'm not sure I completely understand what is wrong here, but I have a some code you can run through the demo and in your browser console to see the difference.

```
var testClass = function(arg1) {this.arg1 = arg1}
testClass.prototype.someMethod = function() {}
testClass.prototype.getNewInstance = function() {
 return new this.constructor('will this be arg1?')
}

alert(new testClass().getNewInstance().someMethod)
alert(new testClass().getNewInstance().arg1)
```

In JS-Interpreter, it seems that `this.constructor` is expected to be called with a proto. If you pass in `this` to the constructor the new instance has the properties from the prototype, but then you can't pass in the arguments to the constructor.

```
var testClass = function(arg1) {this.arg1 = arg1}
testClass.prototype.someMethod = function() {}
testClass.prototype.getNewInstance = function() {
 return new this.constructor(this, 'will this be arg1?')
}

alert(typeof new testClass().getNewInstance().someMethod)   //  This now works!
alert(new testClass().getNewInstance().arg1)   //  This still does not work.
```

**Comment by cpcallen** [comment]
I'm about 90% sure that the problem is that [`.createFunctionBase_`](https://github.com/NeilFraser/JS-Interpreter/blob/master/interpreter.js#L2053) sets `<func>.prototype`, but not `<func>.prototype.consructor` (which should of course be set to `<func>`).

For native functions this oversight is corrected in [`.createNativeFunction`](https://github.com/NeilFraser/JS-Interpreter/blob/master/interpreter.js#L2086), but nowhere does it appear that it is done for user functions.

**Comment by NAllred91** [comment]
`createNativeFunction` can be called with the boolean to make the function not a constructor, but maybe that logic should be moved into `createFunctionBase_` and have the boolean passed through?

In that case, I think `createFunction` could always call `createFunctionBase_` with the boolean set to true?  This is just an assumption though, I think all user functions are constructors but I'm not certain.

**Comment by NAllred91** [comment]
Yea, the comment for `createNativeFunction` points out that some functions can't be called as constructors. I'm unsure if the user can write a function in es5 that can't be called as a constructor though?

I know arrow functions can't be called as constructors, but I'm not sure if there is a way to write a function that can't be called as a constructor is es5?

**Comment by cpcallen** [comment]
> `createNativeFunction` can be called with the boolean to make the function not a constructor, but maybe that logic should be moved into `createFunctionBase_` and have the boolean passed through?
>
> In that case, I think `createFunction` could always call `createFunctionBase_` with the boolean set to true?

There are a few options but that is probably the most straight forward.

> I'm unsure if the user can write a function in es5 that can't be called as a constructor though?

I am not aware of any mechanism by which a user could do that in ES5 (and I am fairly familiar with the spec).

**Comment by NAllred91** [comment]
Yep! this seems to fix the issue I've been running into!

Let me know if you'd like me to make a pull request.

**Comment by NeilFraser** [comment]
I think this should fix it.
