### ISSUE TITLE
Parsing JSON Object.

### ISSUE THREAD

**Issue by DCSDB** [NeilFraser/JS-Interpreter#18]
Hi I am using this with Blockly, great work. I am having trouble parsing JSON objects and to a lesser extent []s. If I return a JSON String from an external call It comes through OK but calling JSON.parse throws an error stating unknown identify JSON. Is there a way around this?

I had a similar problem with arrays and ended up  sending a coma separated string and then splitting it in Blockly, not optimal but it worked :)

Cheers,

David

**Comment by m13253** [comment]
Perhaps you need to export an interface to the sandboxed environment, by defining an external API named `JSON`.

**Comment by NeilFraser** [comment]
Here is a demo showing how to pass JSON in and out of the interpreter:
https://neil.fraser.name/software/JS-Interpreter/demos/json.html
Hope this helps.
