### ISSUE TITLE
Wrong getter behaviour

### ISSUE THREAD

**Issue by XmiliaH** [NeilFraser/JS-Interpreter#184]
The following code will run the getter even if it is not a getter:
```JS
function func() { return 1; }
var obj = {};
Object.defineProperty(obj, 'getter', {get: func, enumerable: true});
var obj2 = { notAGetter: func };

// 1
alert(obj.getter);

// This will set func.isGetter but not clean it up
Object.apply(null, obj);

// 1
alert(obj2.notAGetter);
// should be [object Function], but isGetter was still set
```

**Comment by NeilFraser** [comment]
PR #185 should resolve this issue and explicitly throw in places where we don't support getters and setters.  Good catch on this behaviour, I was aware that we don't support getters and setters in certain places, but I wasn't aware that this could cause this kind of weird behaviour.
