### ISSUE TITLE
How to return a value?

### ISSUE THREAD

**Issue by Cosbgn** [NeilFraser/JS-Interpreter#190]
By default the library returns the last value, however I would like to return at a specific point, something like this:

```
var sunny = true
if (sunny){
return "It's sunny today"
}
return "today is not sunny"
```
This will fail, because the `returns` are not valid, so I tried to wrap them in a function:
```
function x(){
 var sunny....... 
}
x()
```
but also this fails. Any ideas on how this could be done?

**Comment by Cosbgn** [comment]
Never mind, my syntax was wrong. It all works.

**Comment by rrrhys** [comment]
For future weary google travelers:

```
        const expression = "5 + 2";
        const interpreter = new Interpreter(expression);
        interpreter.run()
        const result = interpreter.value;
```
