### ISSUE TITLE
why my app is throwing error when Interpreter.prototype.step() encounters type 'VariableDeclaration'

### ISSUE THREAD

**Issue by pushpalathachenna** [NeilFraser/JS-Interpreter#197]
Help me to get out of this 

TIA

**Comment by NeilFraser** [comment]
Need more information.  What's the error?
Can you give me a sample program that exhibits this problem?

Sent (awkwardly) from an Android device.

**Comment by cpcallen** [comment]
This bug report does not contain enough information for there to be even the slightest possibility of us being able to help you.  Please do a little reading about [how to write a good bug report](https://medium.com/pitch-perfect/how-to-write-the-perfect-bug-report-6430f5a45cd).  At very minimum we need instructions on how to reproduce the error.
