### ISSUE TITLE
Unexpected exception: TypeError: this.functionMap_[type] is not a function

### ISSUE THREAD

**Issue by pushpalathachenna** [NeilFraser/JS-Interpreter#198]
getting the above error when i used this and it's not even giving me proper information to resolve

**Comment by cpcallen** [comment]
You need to give us a complete set of instructions about how to reproduce the error in order for us to be able to help you.  For example, at minimum your bug report must contain a JavaScript program that creates an `Interpreter` instance and then then runs it in a way that produces the exception you are reporting.

I am going to close this bug report, but if you edit it to include instructions on how to reproduce the error I will re-open it.

I will continue to close any future bug reports you file against JS Interpreter which lack steps to reproduce (without further comment).
