### ISSUE TITLE
Are pull requests still being accepted?

### ISSUE THREAD

**Issue by Webifi** [NeilFraser/JS-Interpreter#202]
Looking through the history, it doesn't look like any 3rd party PRs have been merged since 2018.  Are pull requests still accepted, or does @NeilFraser not currently merge or review pull requests other than his own?

Wondering if #201 has any chance of being merged.

**Comment by cpcallen** [comment]
> Are pull requests still accepted, or does @NeilFraser not currently merge or review pull requests other than his own?

In principle, yes, but in practice this project is very, very low priority, and he is unlikely to merge any PR that is not 100% backwards-compatible (i.e., no breaking changes).
