### ISSUE TITLE
Asynchronous result

### ISSUE THREAD

**Issue by BrianGeppert** [NeilFraser/JS-Interpreter#21]
I'm looking to add support for making asynchronous results appear synchronous (specifically, allowing my code to return a Future to the interpreter and having the interpreter wait until the Future is resolved before returning a result to the program being interpreted).  Would you have a preferred API for this?  Would you prefer not using Futures?

**Comment by BrianGeppert** [comment]
I meant Promise, oops.

**Comment by BrianGeppert** [comment]
One complication in my current implementation js that `interpreter.step()` doesn't have a way to indicate “done for now”, and so `interpreter.run()` stops when an async function is encountered.  I'm not concerned about that for my own purposes, but before I submit a PR I'd like to think of a clean solution.

**Comment by BrownBear2** [comment]
I kinda implemented that yesterday. I added a pause() function to the interpreter prototype.
This way you can create a native function that calls pause() and later continue where you stopped by calling run() again. I want to use this to synchronize http requests: create a native function getData() that sends the request and calls interpreter.pause(), then on the web-request callback I call interpreter.run() et voila.

**Comment by NeilFraser** [comment]
I've just implemented createAsyncFunction which should robustly solve this problem.  Let me know if this fits both your needs.

**Comment by NeilFraser** [comment]
Demo of async call:
https://neil.fraser.name/software/JS-Interpreter/demos/async.html

**Comment by BrownBear2** [comment]
I just noticed that the compiled acorn_interpreter.js seems to be missing the createAsyncFunction method
