### ISSUE TITLE
Regular Expression Test Executes Incorrectly

### ISSUE THREAD

**Issue by ghost** [NeilFraser/JS-Interpreter#210]
```
var str = 'table football';

var regex = new RegExp('foo*');
var globalRegex = new RegExp('foo*', 'g');

alert(globalRegex.test(str));
alert(globalRegex.test(str));

```

This code alerts `true` and `true`.
Which is incorrect, it's suppose to alert `true` and `false`.

[Test](https://js.do/PennyMongy/regexp-test)
[Mdn Reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test)

**Comment by cpcallen** [comment]
I've not looked at the code, but this smells of `.lastIndex` not being updated correctly.

**Comment by NeilFraser** [comment]
Confirmed.  Here's a minimal test:
```
var r = /foo*/g;
r.test('table football');
alert(r.lastIndex); 
```
This should alert 9, but JS-Interpreter alerts 0.
