### ISSUE TITLE
New bug in Function wrapper

### ISSUE THREAD

**Issue by Webifi** [NeilFraser/JS-Interpreter#217]
There is a bug in the "Function" wrapper since [b820ad4](https://github.com/NeilFraser/JS-Interpreter/commit/b820ad45134b3ca46e9e7b990a016bd36a654087):

Executing code like the following in the interpreter will result in a "parse_ is undefined" error:
```
var myFn = Function('return true')
```

In interpreter.js starting at [line 539](https://github.com/NeilFraser/JS-Interpreter/blob/740d4d8687b7856b3b9bd5e1fc9e9feaa3e27440/interpreter.js#L539), .parse_ is referenced inside a function like:
```
      var ast = this.parse_('(function(' + argsStr + ') {' + code + '})',
          'function' + (this.functionCodeNumber_++)); 
```

This needs to be changed to:
```
      var ast = thisInterpreter.parse_('(function(' + argsStr + ') {' + code + '})',
          'function' + (thisInterpreter.functionCodeNumber_++)); 
```

**Comment by NeilFraser** [comment]
Thanks for the bug report.  Your solution was correct.  Fixed.

But leaving this bug open since the Closure Compiler is currently throwing errors.  Have filed a bug with Google to get this fixed.  Then I can push the compressed version of JS-Interpreter and close this bug.

**Comment by NeilFraser** [comment]
Recompiled.
