### ISSUE TITLE
Import of interpreter.js broken with new nativeGlobal property

### ISSUE THREAD

**Issue by Webifi** [NeilFraser/JS-Interpreter#218]
Recently, interpreter.js was modified to do [the following](https://github.com/NeilFraser/JS-Interpreter/blob/740d4d8687b7856b3b9bd5e1fc9e9feaa3e27440/interpreter.js#L179):

```
Interpreter.nativeGlobal = this;
```

The problem is that things like RegExp are now broken if interpreter.js is imported using code like:
```
import { Interpreter } from '[your path to interpreter.js]'
```

This could be fixed by changing nativeGlobal to use [globalThis](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis) if it exists, like:
```
Interpreter.nativeGlobal = typeof globalThis === 'undefined' ? this : globalThis;
```

(Since most projects that would use import will likely support globalThis, that seems like the simplest way to solve it.  Otherwise, checking for `globalThis`, `self`, `window`, then `global` would be the more complete solution.)
```
Interpreter.nativeGlobal = 
    typeof globalThis != 'undefined' ? globalThis :
    typeof self != 'undefined' ? self : 
    typeof window != 'undefined' ? window : 
    typeof global != 'undefined' ? global : this;
```

**Comment by NeilFraser** [comment]
Great, thanks!
