### ISSUE TITLE
'modern' alternative to JS-Interpreter?

### ISSUE THREAD

**Issue by TimNZ** [NeilFraser/JS-Interpreter#220]
Turns out it's quite a challenge to google for this.

Are there (newer) alternatives to JS-Interpreter that offer the same support for async as sync and other features, and out of the box ES6+ keywords/statements e.g. let, const?  
Without having to use Babel.

Not supporting ES6+ is not a show stopper, I'm just looking at replicating Google App Scripts language support.

Nothing listed here is an alternative:
https://en.wikipedia.org/wiki/List_of_ECMAScript_engines

Did read this:
https://github.com/NeilFraser/JS-Interpreter/issues/186

CodeCity doesn't look active.

**Comment by TimNZ** [comment]
Read this:
https://github.com/NeilFraser/JS-Interpreter/issues/186

**Comment by brownstein** [comment]
I've actually had a pretty good experience using Babel to pre-process code and a source-map aware wrapper around this library to run and display it. Not perfect (babel generates a lot of code for async functions, which must be crunched by the interpreter), but it works.

See if there's anything you can borrow from https://github.com/brownstein/open-sourceror/tree/master/src/script-runner to meet your needs.

**Comment by TimNZ** [comment]
@brownstein thanks.   Plenty to play with.
