### ISSUE TITLE
Threads demo not working with acorn_interpreter.js

### ISSUE THREAD

**Issue by derwehr** [NeilFraser/JS-Interpreter#225]
When replacing 
```JavaScript
  <script src="../acorn.js"></script>
  <script src="../interpreter.js"></script>
```
with
```JavaScript
  <script src="../acorn_interpreter.js"></script>
```
in [thread.html#L7](https://github.com/NeilFraser/JS-Interpreter/blob/60a12fdb180dfeaf1f94fe6114734c5024745704/demos/thread.html#L7), like described in the [documentation](https://neil.fraser.name/software/JS-Interpreter/docs.html), the demo throws `TypeError: Cannot read properties of undefined (reading 'object')`.

**Comment by NeilFraser** [comment]
Fixed.  Thanks!
