### ISSUE TITLE
Revert back to previous non-blocking state when stuck in a infinit loop

### ISSUE THREAD

**Issue by ChrisAcrobat** [NeilFraser/JS-Interpreter#231]
I have a function in the interpreter which I call externally. If a call timeout I would like to revert the state to what it was before last call so I can call the function again with new set of data and keep the progress of the previous successful executions.
Is there a way to do this today?

**Comment by NeilFraser** [comment]
Yes, you just need to serialize the state of the interpreter.  That way you can restore to that state at any future time.

Serialization demo: https://neil.fraser.name/software/JS-Interpreter/demos/serialize.html

**Comment by ChrisAcrobat** [comment]
Great, thanks!
