### ISSUE TITLE
Passing functions into the interpreter.

### ISSUE THREAD

**Issue by BrownBear2** [NeilFraser/JS-Interpreter#26]
Hi,
I'm trying to infuse a function defined outside the interpreter to work inside. Not like a native function, but actually copy the function body inside. I'm using this code so far (excuse the coffeescript):

      Interpreter.prototype.transferFunction = (scope, name, fn) ->
        ast = acorn.parse "$ = " + fn.toString()

        func = @createObject @FUNCTION
        func.node = ast.body[0].expression.right

        @setProperty func, 'length', @createPrimitive(1), true
        @setProperty scope, name, func

      ip.transferFunction scope, "test",  ->
        return 5 + 5

This works, but when I change data after calling test() in the sandbox, the data I recieve via getProperty() doesn't include those changes. I guess I need to create a new scope for the function and fix the parameter length thingy, but I don't have any idea yet how exactly, so if you could point me in the right direction I would appreciate it. Thanks

**Comment by NeilFraser** [comment]
Rather than using acorn, can I suggest a much simpler approach.  Try this in the demo:
  var f = new Function('alert("Hi")');
  f();
