### ISSUE TITLE
Can we use destructuring?

### ISSUE THREAD

**Issue by F1LT3R** [NeilFraser/JS-Interpreter#261]
I'm not sure if I'm doing something wrong, or whether this is not supported.

I expected the value of `a` inside `resolve` to be the `location`.

```javascript
import interpreter from '/lib/shadow/vendor/interpreter.mjs'

window.log = function (result) {
	console.log({result})
}

var myCode = `
    function resolve ({a}) {
        return a;
    };
    log(resolve({a: url}));

`
var initFunc = function (interpreter, globalObject) {
	interpreter.setProperty(globalObject, 'url', String(location))

	var wrapper = function log(text) {
		return window.log(text)
	}
	interpreter.setProperty(globalObject, 'log', interpreter.createNativeFunction(wrapper))
}
var myInterpreter = new interpreter(myCode, initFunc)
myInterpreter.run()
```

![image](https://github.com/NeilFraser/JS-Interpreter/assets/1218446/39ae3051-a591-4630-8dcf-8e7a3aecbcd5)

**Comment by NeilFraser** [comment]
Destructuring is a feature of ES6: http://es6-features.org/#ParameterContextMatching

JS-Interpreter is ES5 only: https://github.com/NeilFraser/JS-Interpreter/issues/186

**Comment by F1LT3R** [comment]
Got it. Thanks Neil.

Congrats on the great code here and all the work that went into it.

Very impressive!
