### ISSUE TITLE
Try catch syntax does not work correctly when using native syntax

### ISSUE THREAD

**Issue by ayahito-saji** [NeilFraser/JS-Interpreter#263]
Hi, I am using JS-interpreter and have observed that the try-catch syntax does not work correctly and stops with an error in the following case.

```
try {
  new Date(NaN).toISOString();
} catch (e) {
  alert("caught");
}
```

I am guessing the cause is that this program is using the native `toISOString()` and the error occurs outside of the interpreter (native). These errors need to be propagated inside the interpreter, or to be raised internally.

**Comment by ayahito-saji** [comment]
https://github.com/NeilFraser/JS-Interpreter/blob/master/interpreter.js#L1926-L1954

**Comment by NeilFraser** [comment]
Thanks for this report.  Fixed.  I've tested the rest of the Date instance methods, this appears to be the only one that can throw, the rest return either NaN or "Invalid Date".

This class of bug is still lurking in other places.  I'll fix them one by one as they are found.
