### ISSUE TITLE
Support for template literals and tag functions

### ISSUE THREAD

**Issue by rozek** [NeilFraser/JS-Interpreter#273]
First of all: thank you very much for the JS-Interpreter - it helps a lot when JavaScript shall be used for application scripting.

However, I'm missing a few features of "real" JavaScript such as

- template literals (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) and
- tag functions (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#tagged_templates)

Right now, JSI just throws a "SyntaxError: unexpected character '`'"

Are there any plans to support these nifty features?

Thanks in advance for any response!

With greetings from Germany,

Andreas Rozek

**Comment by NeilFraser** [comment]
Template literals are a feature of ES6: https://www.geeksforgeeks.org/introduction-to-es6/#template-literal

JS-Interpreter is ES5 only: https://github.com/NeilFraser/JS-Interpreter/issues/186
