### ISSUE TITLE
Support for Arrow Functions

### ISSUE THREAD

**Issue by rozek** [NeilFraser/JS-Interpreter#274]
Are there plans to support "Arrow Functions" (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions) in the JavaScript Interpreter?

**Comment by NeilFraser** [comment]
Arrow functions are a feature of ES6: https://www.geeksforgeeks.org/introduction-to-es6/#arrow-functions

JS-Interpreter is ES5 only: https://github.com/NeilFraser/JS-Interpreter/issues/186
