### ISSUE TITLE
Support for Proxies?

### ISSUE THREAD

**Issue by rozek** [NeilFraser/JS-Interpreter#275]
Are there plans to support "Proxies" (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) in the JavaScript Interpreter?

**Comment by NeilFraser** [comment]
Proxies are a feature of ES6: https://ponyfoo.com/articles/es6-proxies-in-depth

JS-Interpreter is ES5 only: https://github.com/NeilFraser/JS-Interpreter/issues/186
