### ISSUE TITLE
Support for Primises?

### ISSUE THREAD

**Issue by rozek** [NeilFraser/JS-Interpreter#276]
Are there plans to support "Promises" (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) in the JavaScript Interpreter?

I know that one can wrap asynchronous functions such that there is no need for async/await in an JSI script (which is BRILLIANT!) but sometimes it seems useful to let a function run in the background while the foreground continues working as usual (e.g. handling events)

**Comment by NeilFraser** [comment]
Promises are a feature of ES6: https://www.geeksforgeeks.org/introduction-to-es6/#promises

JS-Interpreter is ES5 only: https://github.com/NeilFraser/JS-Interpreter/issues/186
