### ISSUE TITLE
SetTimeout inside an AsyncFunction

### ISSUE THREAD

**Issue by cthurston** [NeilFraser/JS-Interpreter#28]
I'm trying to implement the AsyncFunction in the latest version.  However, I can't seem to get a simple example working.  Does this work with SetTimeout?  

'next' gets called but execution doesn't seem to continue. 

```
//For some reason this does not work.
    var wrapper = function(d, next) {
        window.setTimeout(function() {
            next();
        }, d);
    };
    interpreter.setProperty(scope, 'wait',
        interpreter.createAsyncFunction(wrapper));
```

Code passed to the interpreter.

```
wait(2000);
alert('Continued');
```

**Comment by BrownBear2** [comment]
That's because you have to call interpreter.run() in your async callback.
See here:
https://github.com/NeilFraser/JS-Interpreter/pull/39

**Comment by eliteslayer10** [comment]
You could rather use the 'sleep' function using ES6 promise.
