### ISSUE TITLE
How to get an array object from an external function?

### ISSUE THREAD

**Issue by jcubic** [NeilFraser/JS-Interpreter#280]
I have code like this:

```javascript
test('it should create and interate over array', () => {
    const fn = vi.fn();
    const code = 'var x = [1,2,3]; alert(x);';
    const inter = new Interpreter(code, (interpreter, globalObject) => {
        const native_fn = interpreter.createNativeFunction(fn);
        interpreter.setProperty(globalObject, 'alert', native_fn);
    });
    inter.run();
    expect(fn.mock.calls[0]).toEqual([[1,2,3]]);
});
```

But I got weird object that look like this:

```diff
- Expected
+ Received

  Array [
-   Array [
-     1,
-     2,
-     3,
-   ],
+   Object {
+     "class": "Array",
+     "getter": Object {},
+     "properties": Object {
+       "0": 1,
+       "1": 2,
+       "2": 3,
+     },
+     "proto": Object {
+       "class": "Array",
+       "getter": Object {},
+       "properties": Object {},
+       "proto": Object {
+         "getter": Object {},
+         "properties": Object {},
+         "proto": null,
+         "setter": Object {},
+       },
+       "setter": Object {},
+     },
+     "setter": Object {},
+   },
  ]
```

Is there a builtin way to convert this into a real array?

I can use `Object.values(object.properties)` but I think it would be good idea to convert this when calling function from external API. I'm not familiar with the internals and architecture, so I don't know if this is possible or not. If there are any limitations that don't allow passing a real Array into an external function, let me know.

**Comment by NeilFraser** [comment]
I believe you will find these two functions very helpful:

pseudoToNative: https://github.com/NeilFraser/JS-Interpreter/blob/master/interpreter.js#L2676
nativeToPseudo: https://github.com/NeilFraser/JS-Interpreter/blob/master/interpreter.js#L2602
