### ISSUE TITLE
Array.prototype.splice issue

### ISSUE THREAD

**Issue by joshlory** [NeilFraser/JS-Interpreter#29]
https://neil.fraser.name/software/JS-Interpreter/
```javascript
var a = 'a b c d e f'.split(' ');
a.splice(3, 1);
alert(a);
```

Expected: `["a", "b", "c", "e", "f"]`
Actual: `TypeError: Cannot read property 'toString' of undefined`

**Comment by BrownBear2** [comment]
fixed this here https://github.com/NeilFraser/JS-Interpreter/pull/38
