### ISSUE TITLE
I'm confused about 'child.parent.prototype'

### ISSUE THREAD

**Issue by NewLisper** [NeilFraser/JS-Interpreter#31]
<pre><code>
Interpreter.prototype.isa = function(child, parent) {
  if (!child || !parent) {
    return false;
  } else if (child.parent == parent) {
    return true;
  } else if (!child.parent || !child.parent.prototype) {
    return false;
  }
  return this.isa(child.parent.prototype, parent);
};
</code></pre>
'child.parent' is a constructor object which has prototype property in 'properties'.
Maybe you should use 'child.parent.properties.prototype'  here?

**Comment by NeilFraser** [comment]
Correct.  This was fixed in 9e8312cfb275ff1abc9d96ad1c8c0ae19d1c57f2.  Thanks!
