### ISSUE TITLE
Interpreter does not support multiple assignment 

### ISSUE THREAD

**Issue by amrdraz** [NeilFraser/JS-Interpreter#32]
An expressions such as
var a = b = c =  10;

does not work and throws an error 'b' is undefined

and assignment like this should be evaluated as
var a = (b = (c = 10));

instead the interpreter tries to evaluate b as a variable and get its value

**Comment by joshlory** [comment]
I think the issue is that `b` and `c` aren't defined yet.  It works if you define all three vars first:

```javascript
var a, b, c;
a = b = c = 5;
alert([a,b,c]);
```
Alerts: [5, 5, 5]

**Comment by amrdraz** [comment]
Oh then the interpreter does not support global assignment ^_^;

`a = 2` operation as opposed to `var a = 2`

This means the interpreter is basically running in strict mode, is there a way to support this?

I don't have full control over the generated script that's passed, I did work around it by pre registering the variables before in the initAPI function.

tho now I have the other issue of not being able to call the functions within that variable (an Object)

**Comment by amrdraz** [comment]
but doesn't the JavaScript language dictate that they should be considered
global variables and then defined in the global scope?

*Amr Draz*
*Teaching Assistant German University in Cairo (GUC)*

*Mobile:* (+2) (01001132292)   |   *LinkedIn: *[Profile
<http://eg.linkedin.com/in/amrdraz>] | *Skype: * (bing91)

**Comment by NeilFraser** [comment]
It depends on whether JS is in strict mode or not.  Strict mode throws an error, regular mode does not.  I've accepted BrownBear2's patch that takes the interpreter out of strict mode, resolving this issue.

Next I'll look at adding a 'use strict' flag so that the interpreter can be in either mode, as needed.

**Comment by NeilFraser** [comment]
'use strict' is now supported.  So you can choose either behaviour as needed.
(Haven't pushed a compiled version of this yet as I'm expecting other updates.)

**Comment by amrdraz** [comment]
I see, very intresting thanks

On Saturday, October 17, 2015, Neil Fraser <notifications@github.com> wrote:

> 'use strict' is now supported. So you can choose either behaviour as
> needed.
> (Haven't pushed a compiled version of this yet as I'm expecting other
> updates.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NeilFraser/JS-Interpreter/issues/32#issuecomment-148949195>
> .
>


-- 
*Amr Draz*
*Teaching Assistant German University in Cairo (GUC)*

*Mobile:* (+2) (01001132292)   |   *LinkedIn: *[Profile
<http://eg.linkedin.com/in/amrdraz>] | *Skype: * (bing91)
