### ISSUE TITLE
"makePredicate" without "new Function"?

### ISSUE THREAD

**Issue by retorquere** [NeilFraser/JS-Interpreter#35]
I want to include acorn in a Firefox extension, and for signing purposes I want to avoif the constructs "eval" and "new Function". The only place I see it used in acorn is at https://github.com/NeilFraser/JS-Interpreter/blob/master/acorn.js#L354, and the comment above that function indicate that it is perhaps only done for speed reasons. I'm all for speed, would it be possible for me to re-implement makePredicate using something like a split + a loop, or even a regex?

**Comment by retorquere** [comment]
I see acorn actually comes from https://github.com/marijnh/acorn; Marijn offers a separate parser (acorn_csp) that would solve this problem for me. Would it be possible to have an acorn_csp_interpreter build?

**Comment by NeilFraser** [comment]
There's not much of a build process, just concatenate acorn.js and interpreter.js and smash the result through the JS minifier of your choice (Packer is good: http://dean.edwards.name/packer/).  I'd rather not end up providing multiple binaries in the repo when they are simple to do by the end developer.
