### ISSUE TITLE
String.prototype.replace is not implemented

### ISSUE THREAD

**Issue by joshlory** [NeilFraser/JS-Interpreter#50]
On: https://neil.fraser.name/software/JS-Interpreter/
```javascript
alert('abc'.replace('b', ''));
```
Throws: "Uncaught TypeError: undefined is not a function"

**Comment by anhh** [comment]
on Interpreter.prototype.initString function put replace code like below.

  wrapper = function(substr, newSubStr) {
    var str = this.toString();
    if (substr) {
      substr = thisInterpreter.isa(substr, thisInterpreter.REGEXP)
                  ? substr.data : substr.toString();
    } else {
      substr = undefined;
    }

    if (newSubStr) {
      newSubStr = thisInterpreter.isa(substr, thisInterpreter.STRING)
                  ? newSubStr.toString() : undefined;
    } else { // is this really necessary?
      newSubStr = undefined;
    }

	return thisInterpreter.createPrimitive(substr && newSubStr ? str.replace(substr, newSubStr) : str);
  };
  this.setProperty(this.STRING.properties.prototype, 'replace',
                   this.createNativeFunction(wrapper), false, true);

**Comment by NeilFraser** [comment]
Thanks.  I thought it was already implemented.  Fixed (though callback functions are not supported, the documented workaround for Array.sort works here too).

Pushed to repo, but not deployed or compiled yet.
