### ISSUE TITLE
Throw Error instead of String

### ISSUE THREAD

**Issue by bioball** [NeilFraser/JS-Interpreter#53]
`Error`s contain much more useful information, like the stack trace at the point of creating the `Error`. It's much harder to track these errors down when just strings are thrown.

I'd be happy to submit a PR for this.

**Comment by BrownBear2** [comment]
Hm, I thought someone already reported or fixed that, but I can't find anything. But yeah, I don't see a reason not to throw Errors.

**Comment by greenSnot** [comment]
I have the same problem.

**Comment by NeilFraser** [comment]
Fixed.

**Comment by bioball** [comment]
@NeilFraser I'm still noticing that strings are thrown. For example, here:
https://github.com/NeilFraser/JS-Interpreter/blob/master/interpreter.js#L73

My suggestion is instead of this:

```js
throw 'Expecting original AST to start with a Program node.';
```

It should be:

```js
throw new Error('Expecting original AST to start with a Program node.');
```

**Comment by NeilFraser** [comment]
Oh, I see what you mean.  I was referring to errors inside the sandbox, you were referring to errors outside the sandbox.  Done.

Though I've used:
```
throw Error('Expecting original AST to start with a Program node.');
```
since I don't see the need for the `new` keyword.

**Comment by bioball** [comment]
Ah, sweet! 👍 

Didn't realize that the error constructor doesn't need a `new` keyword. Cool.
