### ISSUE TITLE
Running Headless

### ISSUE THREAD

**Issue by TechplexEngineer** [NeilFraser/JS-Interpreter#59]
I'm attempting to use the JS-Interpreter in an environment that doesn't have a window variable. For now I've just added a shim `var window = {}` which allows the code to run without error. Is there a better way to handle this?

**Comment by NeilFraser** [comment]
Fixed.
https://github.com/NeilFraser/JS-Interpreter/commit/1544697ce6fa7a799f2cd1be7717ae3239dbcd33
