### ISSUE TITLE
array.sort() not implemented

### ISSUE THREAD

**Issue by HarleyKwyn** [NeilFraser/JS-Interpreter#6]
I may work on this eventually.

**Comment by NeilFraser** [comment]
Sort now works if there is no custom comparator function.  If there is a comparator function, then here's a demo of monkey patching the required code:
https://neil.fraser.name/software/JS-Interpreter/demos/sort.html

**Comment by ecampver** [comment]
I know I said I'd work on finishing the sort function, sorry, I've been really really busy. With some luck I might get this done in 2 or 3 weeks. I'll implement that exact same bubble sort as in the demo but inside the interpreter as you suggested a while ago.
