### ISSUE TITLE
Debugger type actions

### ISSUE THREAD

**Issue by TechplexEngineer** [NeilFraser/JS-Interpreter#60]
Is there any way to "Step over" a line rather than go through all of the parse steps involved in that line?

In the [Blockly Demo: Js Interpreter ](https://blockly-demo.appspot.com/static/demos/interpreter/index.html) it looks like one methods is to inject hilightBlock(%1) before every statement. Is this the best way to implement line by line stepping?

**Comment by NeilFraser** [comment]
Yes, you'd want to do something like this:
```
while (myInterpreter.stateStack[0].node.type != 'ExpressionStatement') {
  myInterpreter.step();
}
```

Some tweaking is needed so it doesn't get stuck, but that's the general idea.
