### ISSUE TITLE
How to set a global variable?

### ISSUE THREAD

**Issue by greenSnot** [NeilFraser/JS-Interpreter#63]
I have multi interpreter instances,
```
var code1='var x=1;';
var code2='var y=2;';
var interpreterA=new Interpreter(code1);
var interpreterB=new Interpreter(code2);
```
I wanna get x from interpreterB but they are in different sandbox,so I wanna set "global variable" for all the interpreters.

**Comment by NeilFraser** [comment]
Instead of a variable, create a pair of getter and setter methods that access a shared variable outside the sandboxes.
