### ISSUE TITLE
Unable to call new functions added with appendCode

### ISSUE THREAD

**Issue by gotdan** [NeilFraser/JS-Interpreter#69]
I can call existing functions from code added to an interpreter with appendCode, but if I add a new function I'm unable to call it. 

For example, the following code throws "ReferenceError: test is not defined":
```
var int = new Interpreter("");
int.appendCode(  "function test(){}; test();" );
int.run();
```

This code works fine:
```
var int = new Interpreter( "function test(){};" );
int.appendCode( "test();" );
int.run();
```

**Comment by NeilFraser** [comment]
Fixed.  Thanks!
