### ISSUE TITLE
`for ... in ...` reveals array method names too

### ISSUE THREAD

**Issue by benjie** [NeilFraser/JS-Interpreter#77]
Using the [interpreter demo](https://neil.fraser.name/software/JS-Interpreter/) and entering:

```js
var result = [];
var foo = [
  {a: 1},
  {b: 2},
  {c: 3}
];
for (var i in foo) {
  result.push(i);
}
alert(result.join(', '));
```

Gives the result:

```
0, 1, 2, every, filter, forEach, map, reduce, reduceRight, some, sort, toLocaleString
```

Expected result (e.g. what Chrome gives) is

```
0, 1, 2
```

(I recognise that `for ... in ...` shouldn't be used for looping over arrays, and that this can be solved by wrapping with `foo.hasOwnProperty(i)` but since it differs from a modern JS engine I thought you might be interested to know.)

**Comment by benjie** [comment]
This might be fixed by https://github.com/NeilFraser/JS-Interpreter/commit/08f81e7fe657d852a65fa9889a7a8861dfe90fc6

**Comment by NeilFraser** [comment]
Correct, this was fixed as a result of a bug reported by Blockly.  I'll do a recompile later today so that the compressed package gets updated.

**Comment by benjie** [comment]
Very impressive response time, thanks Neil!
