### ISSUE TITLE
Interpreter is stepping through polyfill code

### ISSUE THREAD

**Issue by islemaster** [NeilFraser/JS-Interpreter#78]
As of 08f81e7fe657d852a65fa9889a7a8861dfe90fc6 the `step()` method is stopping inside polyfilled code like `Array.prototype.sort`.

The root cause seems to be that node locations are not getting stripped properly.  The interpreter [checks for a node `.end` location to decide whether the node is in user code](https://github.com/NeilFraser/JS-Interpreter/blob/master/interpreter.js#L152), but I'm seeing nodes with end locations well outside of user code (probably in polyfill code).  I did some quick instrumentation and found [that the call to `stripLocations_` from the polyfill code](https://github.com/NeilFraser/JS-Interpreter/blob/master/interpreter.js#L64) is missing a lot of nodes.

* At c08300d running `new Interpreter('')` it strips locations from 860 nodes.
* At 08f81e7fe657d852a65fa9889a7a8861dfe90fc6 it only strips locations from 101 nodes.

I don't totally understand the root cause or have a fix yet, but if I come up with one I'll submit it here.  Thanks!

**Comment by islemaster** [comment]
After a little more exploration, I'm wondering if the `"ObjectExpression"` from the polyfill isn't being parsed correctly by acorn 0.4.1.  The third argument `{configurable: true, value: function () { ... }}` is being parsed like this:

![screenshot from 2016-09-13 17-20-16](https://cloud.githubusercontent.com/assets/1615761/18495919/601acb9a-79d6-11e6-90d7-6af5d859333a.png)

But I _think_ `properties` is supposed to be an array of `Property` which should also be a `node_t` ([according to the ESTree Spec](https://github.com/estree/estree/blob/master/es5.md#objectexpression)) instead of a plain `Object`.

This seems to be where `stripLocations_` is breaking down - while iterating through array members it [checks that members are interpreter nodes](https://github.com/NeilFraser/JS-Interpreter/blob/master/interpreter.js#L2320) and stops descending if they are not, but in this case the array members are plain objects that contain interpreter nodes (the `key` and `value`) and those nodes and all of their descendants - including the bodies of the polyfilled functions - do not get stripped.

I've tried a special-case workaround for this in `stripLocations_`.  It seems to get things working again and the number of stripped nodes jumps back up to 922, which seems right.  However, I'd also like to try upgrading acorn to see if the behavior goes away.  Certainly [their tests (warning, slow page!)](https://github.com/ternjs/acorn/blob/master/test/tests.js#L1630) seem to suggest the behavior has changed since 0.4.1.

```javascript
      // Speculative fix, L2318
      if (node.type == 'ObjectExpression' && prop instanceof Array) {
        for (var i = 0; i < prop.length; i++) {
          if (prop[i] && prop[i].key && prop[i].key.constructor == parent) {
            this.stripLocations_(prop[i].key);
          }
          if (prop[i] && prop[i].value && prop[i].value.constructor == parent) {
            this.stripLocations_(prop[i].value);
          }
        }
      } else if (prop instanceof Array) { ... }
```

**Comment by NeilFraser** [comment]
Good catch and good analysis.  I've pushed a simpler fix that should be more robust: https://github.com/NeilFraser/JS-Interpreter/commit/4b8e5f1c51a14ab3f6077e3bd1aa4b8f53235b4b

The version of Acorn we have is the last version prior to a major rewrite that allowed it to parse ES6.  Since this interpreter does not run ES6 code (Promise, WeakMap, etc) this would simply add bloat and complexity.

**Comment by islemaster** [comment]
Thanks for the quick fix, this looks great!
