### ISSUE TITLE
Thrown TypeError 'undefined is not a function' not caught by try/catch

### ISSUE THREAD

**Issue by benjie** [NeilFraser/JS-Interpreter#79]
Running this in https://neil.fraser.name/software/JS-Interpreter/index.html demonstrates the issue:

```js
try {
  var foo = {};
  var bar = foo.nx.map(function(baz) {return baz['qux'];})
} catch (e) {
  alert("CAUGHT");
}
```

Because `foo.nx` is undefined the `var bar` line throws `TypeError: undefined is not a function` which *should* be caught by the `try{}catch(e){}`.

### Expected

Should see the modal alert in the browser.

### Actual

Error is uncaught by the `try{}catch(e){}` block within JS-Interpreter; is raised in the host javascript environment instead.

**Comment by NeilFraser** [comment]
Fixed.  Thanks for the report!
In the process I found that finally isn't called when an error is thrown.  Will fix that next.
The compiled version will be updated once this second issue is resolved.

**Comment by NeilFraser** [comment]
The 'finally' issues have now been resolved and the compiled version is updated.
