### ISSUE TITLE
Object.prototype.hasOwnProperty.call(null, 'foo') not caught by try/catch

### ISSUE THREAD

**Issue by benjie** [NeilFraser/JS-Interpreter#81]
Hi Neil, I found another one.

To reproduce, enter the following code in https://neil.fraser.name/software/JS-Interpreter/index.html :

```javascript
try {
Object.prototype.hasOwnProperty.call(null, 'foo');
alert('done');
} catch (e) {
alert('error');
}
```

Should result in an alert, actually results in an error in the javascript console.

![screenshot 2016-10-08 15 19 44](https://cloud.githubusercontent.com/assets/129910/19213695/a9731bd8-8d6a-11e6-8f8d-22b4b50da28f.png)

**Comment by benjie** [comment]
This is another one, involving `isGetter`:

```js
try {
  var foo = {};
  if (true) {
    alert((foo.a || foo.b).c);
  }
} catch(e) {
  alert('caught ' + e.message);
}
```


![screenshot 2016-10-08 15 18 36](https://cloud.githubusercontent.com/assets/129910/19213690/81b5c910-8d6a-11e6-8fd0-efe6ab3c7b5f.png)

**Comment by benjie** [comment]
More edge cases; `JSON.parse(undefined)`:

```js
try {
JSON.parse(undefined);
} catch (e) {
alert('caught');
}
```

![screenshot 2016-10-08 15 22 47](https://cloud.githubusercontent.com/assets/129910/19213716/1e3a10ca-8d6b-11e6-9ac1-da45e6db8e20.png)

**Comment by NeilFraser** [comment]
First and third errors are now caught.  Will deal with the second one tomorrow.

**Comment by benjie** [comment]
Great work Neil! Sorry to be the source of so many reports - especially given most blockly workflows probably won't trigger them! Is the format of the bug reports above the most useful to you, or can I do something to improve them?

Your [demo page](https://neil.fraser.name/software/JS-Interpreter/index.html) has been super-useful for tracking these down to produce minimal test-cases 👍

**Comment by NeilFraser** [comment]
Second bug caught.

Thanks for reporting these!  All I need is the code snippet to be pasted into index.html (and pasted into the console for comparison).  No need for a screenshot.
