### ISSUE TITLE
Error thrown in catch block causes issue in `Interpreter.prototype.executeException`

### ISSUE THREAD

**Issue by benjie** [NeilFraser/JS-Interpreter#82]
Sorry about this, whilst debugging an issue I came across this and thought you'd want to know

To reproduce:

```js
try {
  throw new Error("Foo");
} catch(e) {
  throw e;
}
```

![screenshot 2016-10-08 15 05 11](https://cloud.githubusercontent.com/assets/129910/19213637/a0ecd906-8d68-11e6-84e1-e0593a4ac0e1.png)

Looks like you just need a `state &&` in that `if` clause?

Also `} while (state || state.node.type == 'Program');` looks wrong - perhaps you meant `&&`?

**Comment by NeilFraser** [comment]
Yup, fixed in PR #80.  Sorry about that.
