### ISSUE TITLE
Reduce not working correctly

### ISSUE THREAD

**Issue by gophercall** [NeilFraser/JS-Interpreter#86]
The reduce implementation doesn't yield the expected output.

E.g. in the [interpreter demo](https://neil.fraser.name/software/JS-Interpreter/) I tried this without any output: 

```
var numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

var sum = numbers.reduce(function(prev, curr) { return prev + curr; }, 0);

alert(sum);
```

This [example from MDN](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce#Sum_all_the_values_of_an_array) also doesn't work:

```
var sum = [0, 1, 2, 3].reduce(function(a, b) {
  return a + b;
}, 0);

alert(sum)
```

**Comment by NeilFraser** [comment]
The issue is that 'this' is not getting set in the 'map' polyfill.  That's pretty serious.  Investigating...

**Comment by NeilFraser** [comment]
Fixed, thanks!
Will build a compressed package shortly.
