### ISSUE TITLE
Switch statement buggy

### ISSUE THREAD

**Issue by droidery** [NeilFraser/JS-Interpreter#87]
The switch statement implementation doesn't correctly yield the expected output.

For example, this code from MDN, alerts `'This animal will not.'` rather than `'This animal will go on Noah\'s Ark.'`
```
var Animal = 'Giraffe';
switch (Animal) {
  case 'Cow':
  case 'Giraffe':
  case 'Dog':
  case 'Pig':
    alert('This animal will go on Noah\'s Ark.');
    break;
  case 'Dinosaur':
  default:
    alert('This animal will not.');
}
```

**Comment by anonpoet** [comment]
I've tracked down this bug.  It looks like it's a side-effect of the October 26th commit. If a or b is a string, isNan() will return true and the comp function will return NaN.  I'm reverting back to the old function.

  if ( (a.isPrimitive && isNaN(a.data)) ||
      (b.isPrimitive && isNaN(b.data)) ) {
    // NaN is not comparable to anything, including itself.
    return NaN;
  }

**Comment by NeilFraser** [comment]
Fixed, thanks!
Will build a compressed package shortly.
