### ISSUE TITLE
Is it possible to call a sandbox function from a native function exposed to the interpreter?

### ISSUE THREAD

**Issue by ferrao** [NeilFraser/JS-Interpreter#88]
I have the need to execute some user created code, which is valid inside the sandbox, uses existing sandbox objects and functions, but from within a native function, exported into the sandbox as well.

I have gone through docs and code but can not figure out how to do it, would appreciate any suggestion regarding this.

**Comment by BrownBear2** [comment]
Check out my previous issues/pull requests.

**Comment by ferrao** [comment]
I did @BrownBear2, but I am still unable to achieve this. Have you managed it?

**Comment by ferrao** [comment]
I believe #102 is exactly what I was looking for!
