### ISSUE TITLE
Thanks 4 this usefull library ...

### ISSUE THREAD

**Issue by coldev** [NeilFraser/JS-Interpreter#89]
Thanks 4 this usefull library ...

Thank you...

Ask only a one question.. is possible declare any new functions ?
as  func1, func2 , etc ?

var myInterpreter = new Interpreter(myCode,  func1, func2 , etc );

**Comment by carloslfu** [comment]
If what you want is to define functions for using inside the interpreted code you can use the External API that is documented in the [docs page](https://neil.fraser.name/software/JS-Interpreter/docs.html). With that you can add a primitive and execute external code.
