### ISSUE TITLE
function.prototype.bind is not implemented

### ISSUE THREAD

**Issue by chughes87** [NeilFraser/JS-Interpreter#9]

**Comment by georules** [comment]
As far as I can tell, this gives bind functionality:

https://github.com/georules/JS-Interpreter/commit/10507eb78629b8ecabfbc3c4d3f84e40e26973fd

However, I don't know if this creates some security problems.  I tested the functionality with the following code pasted into the JS-Interpreter Demo (index.html)

```
var x = {x:100}
var f = function() {
alert(this.x)
}
f.bind(x)()
```

**Comment by BrownBear2** [comment]
Your change will call() the function not bind() it. You still get the alert, because it's called. But the the return value is also called, so you should get an error message in your console saying undefined is not a function or similar.

**Comment by georules** [comment]
If you test it, you will find that it alerts 100, indicating that this was bound to the x object.

**Comment by georules** [comment]
While we do get the error, we also get the expected value to display in the alert.  Why is this?

**Comment by BrownBear2** [comment]
bind() is supposed to return a function, that when called, has it's this object and arguments set to what you specified. Your code just is a alias for call(). So the function is called and returns undefined in your case. Then you call the return value, which throws an error.

**Comment by georules** [comment]
I see now -- I was misinterpreting my output.  Do you know of any limitations are there to solve supporting bind correctly?  I'll think more about it to see if I can solve it.

**Comment by BrownBear2** [comment]
You would need to store the thisObject and arguments in a new type of bound function node and prepend those args etc when a call to that function is issued.

**Comment by NeilFraser** [comment]
Bind is now supported.
