### ISSUE TITLE
Multiple labels are legal

### ISSUE THREAD

**Issue by cpcallen** [NeilFraser/JS-Interpreter#92]
The following is legal and works as expected:

    foo:
    bar:
    while(true) {
        break foo;
    }

JS-interpreter give "Uncaught SyntaxError: Illegal break statement" because the outer LabeledStatement node writes its label to the inner one, which ignores it and writes its own label onto the ForStatement node; both LabeledStatements have been popped by the time the break statement executes.

**Comment by NeilFraser** [comment]
Good catch.  Thanks!
